### ISSUE TITLE
Request for Pre-trained Weights

### ISSUE THREAD

**Issue by WangJunjie97** [haoqiwang/sinder#1]
I want to thank you for sharing your great work and open sourcing the code. It was very helpful in my research.

I'm currently following your work and I believe getting pre-trained weights will greatly benefit my progress. Can you share the pre-training weights for this program?

Thank you very much for your time and consideration.

**Comment by haoqiwang** [comment]
Updated in README. Thanks!

**Comment by hiyyg** [comment]
Could you please also provide some sample code for loading the pretrained weights into the model? @haoqiwang 

```
ckpt = torch.load("model.pt")
model_name = "dinov2_vitg14"
model = torch.hub.load(
             repo_or_dir=Path(sinder.__file__).parent.parent,
             source='local',
             model=model_name,
         )
model.load_state_dict(ckpt)
```

Error:
```
RuntimeError: Error(s) in loading state_dict for DinoVisionTransformer:
        Unexpected key(s) in state_dict: "reg_token".
```
