### ISSUE TITLE
Reproduce the example figures

### ISSUE THREAD

**Issue by TumVink** [haoqiwang/sinder#4]
Heyy, Thanks for the great project.

However I am curious how to re-produce the example figures using scripts?
![image](https://github.com/user-attachments/assets/4b75b982-543f-4d92-a900-f8895ed3c771)

**Comment by haoqiwang** [comment]
Visualization code pushed. Please check out the README.

**Comment by TumVink** [comment]
Thanks for your update! Appreciate it!
