### ISSUE TITLE
Improvement on Unsupervised Segmentation

### ISSUE THREAD

**Issue by rd1886** [haoqiwang/sinder#5]
Hi,

I noticed in your paper that you've achieved improved results in unsupervised segmentation using STEGO and CAUSE. Will you also be publishing the code for this?

Thank you!

**Comment by haoqiwang** [comment]
We used the official code repo for STEGO(https://github.com/mhamilton723/STEGO) and CAUSE(https://github.com/ByungKwanLee/Causal-Unsupervised-Segmentation). You can find the hyperparameters in appendix of our paper.
